
package scheduler.ws;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
@WebFault(name = "InvalidFormatException", targetNamespace = "http://ws.scheduler/")
public class InvalidFormatException_Exception extends Exception {

    /**
     * Java type that goes as soapenv:Fault detail element.
     *
     */
    private InvalidFormatException faultInfo;

    /**
     *
     * @param faultInfo
     * @param message
     */
    public InvalidFormatException_Exception(String message, InvalidFormatException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidFormatException_Exception(String message, InvalidFormatException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     *
     * @return
     *     returns fault bean: scheduler.ws.InvalidFormatException
     */
    public InvalidFormatException getFaultInfo() {
        return faultInfo;
    }

}
