
package scheduler.ws;

import javax.xml.ws.Response;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 *
 */
public interface SchedulerMainAsyncHandler {


    /**
     *
     * @param response
     */
    public void onSchedulerTsOutWSResponse(Response<SchedulerTsOutWSResponse> response);

    /**
     *
     * @param response
     */
    public void onSchedulerTsInWSResponse(Response<SchedulerTsInWSResponse> response);

    /**
     *
     * @param response
     */
    public void onSchedulerExportRequestWSResponse(Response<SchedulerExportRequestWSResponse> response);

    /**
     *
     * @param response
     */
    public void onSchedulerRemoveTempFileWSResponse(Response<SchedulerRemoveTempFileWSResponse> response);

}
